apiVersion: v1
kind: ServiceAccount
metadata:
  name: krp-curl-verb-override
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-rbac-proxy-verb-override-client
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]  # Note: "list" permission required, not "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-rbac-proxy-verb-override-client
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-rbac-proxy-verb-override-client
subjects:
- kind: ServiceAccount
  name: krp-curl-verb-override
  namespace: default
