apiVersion: batch/v1
kind: Job
metadata:
  name: krp-curl-verb-override
spec:
  template:
    metadata:
      name: krp-curl-verb-override
    spec:
      serviceAccountName: krp-curl-verb-override
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: krp-curl
        image: quay.io/brancz/krp-curl:v0.0.2
        env:
        - name: SERVICE_URL
          value: "https://kube-rbac-proxy-verb-override.default.svc:8443"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      restartPolicy: Never
      volumes:
      - name: tmp
        emptyDir: {}
  backoffLimit: 4
